version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: taelar.io
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules # Garde node_modules isolé dans le container
    tty: true
    stdin_open: true
    restart: unless-stopped
    mem_limit: 1g
    cpus: 2
